// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlvkPADukilLD2OC28bsPuO_wG8o-HTQk',
    appId: '1:477136227844:android:e3ff3d4bd902b1e22c6f51',
    messagingSenderId: '477136227844',
    projectId: 'taxify-43666',
    storageBucket: 'taxify-43666.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoOmyca-oQByxQQtxBFqLpsLrsGEE613U',
    appId: '1:477136227844:ios:697068b9ee697fc42c6f51',
    messagingSenderId: '477136227844',
    projectId: 'taxify-43666',
    storageBucket: 'taxify-43666.firebasestorage.app',
    iosBundleId: 'com.example.taxifyUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoOmyca-oQByxQQtxBFqLpsLrsGEE613U',
    appId: '1:477136227844:ios:697068b9ee697fc42c6f51',
    messagingSenderId: '477136227844',
    projectId: 'taxify-43666',
    storageBucket: 'taxify-43666.firebasestorage.app',
    iosBundleId: 'com.example.taxifyUser',
  );
}
