name: taxify_user
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.5
  location: ^8.0.0
  permission_handler: ^11.4.0
  dio: ^5.8.0+1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  shimmer: ^3.0.0
  google_maps_flutter: ^2.12.0
  flutter_launcher_icons: ^0.14.3
  go_router: ^14.8.1
  get_it: ^8.0.3
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3
  toastification: ^3.0.2
  cached_network_image: ^3.4.1
  webview_flutter_plus: ^0.4.15
  flutter_local_notifications: ^19.0.0
  cloud_firestore: ^5.6.6
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_google_maps_webservices: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: PlusJakarta
      fonts:
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-ExtraBoldItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-MediumItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
